#!/bin/bash
# thi is the general script to understand the input and output interaction mode with the users
# author : jagath

host=hostname
echo
echo " Hi subscribers, this is $host "
echo
echo " what is your name"
echo
read name
echo "hello $name"
